spring.datasource.url=jdbc:mysql://localhost:3306/body_paint_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Juancruzgta5
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# esto es para que hibernate y no romap las tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# ver punto 2: si no le ponemos el dialecto puede tirar error de coneccion
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8081